# Generated by Django 4.2.26 on 2025-11-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_espacios_academicos', '0007_solicitud_acepta_condiciones_uso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='acepta_ley_259',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='firma_digital',
        ),
        migrations.AddField(
            model_name='espaciocampus',
            name='documento_condiciones',
            field=models.FileField(blank=True, help_text='Sube el PDF con las condiciones de uso del espacio', null=True, upload_to='condiciones_espacios/', verbose_name='Documento de Condiciones de Uso'),
        ),
    ]
