# Generated by Django 4.2.26 on 2025-11-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_espacios_academicos', '0006_solicitud_eliminada_solicitud_fecha_eliminacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='acepta_condiciones_uso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='acepta_ley_259',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_aceptacion_terminos',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='firma_digital',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='ip_aceptacion',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
