# Generated by Django 4.2.23 on 2025-08-31 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_espacios_academicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='archivo_adjunto',
            field=models.FileField(blank=True, help_text='Archivo adjunto (PDF, imagen, etc.)', null=True, upload_to='solicitudes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='espacio_campus',
            field=models.ForeignKey(blank=True, help_text='Espacio de campus (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='gestion_espacios_academicos.espaciocampus'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo_espacio',
            field=models.CharField(choices=[('carrera', 'Espacio de Carrera'), ('campus', 'Espacio de Campus')], default='carrera', help_text='Tipo de espacio solicitado', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='espacio',
            field=models.ForeignKey(blank=True, help_text='Espacio de carrera (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='gestion_espacios_academicos.espacio'),
        ),
    ]
