# Generated by Django 4.2.24 on 2025-10-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_espacios_academicos', '0002_solicitud_archivo_adjunto_solicitud_espacio_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token_verificacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
