# Generated by Django 4.2.26 on 2025-11-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_espacios_academicos', '0003_customuser_token_expira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando el encargado aprobó la solicitud', null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se envió la confirmación', null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='token_confirmacion',
            field=models.CharField(blank=True, help_text='Token único de confirmación', max_length=16, null=True),
        ),
    ]
