# Generated by Django 4.2.26 on 2025-11-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_espacios_academicos', '0005_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='eliminada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
